name: Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shell-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check shell script syntax
        run: |
          find . -name '*.sh' -print0 | xargs -0 -n1 bash -n
